### LOCALHOST
GET http://localhost:3000
content-type: application/json

### QRCode
### findAll()
GET http://localhost:3000/qrcodes
content-type: application/json

### findOne()
GET http://localhost:3000/qrcodes/6fa03cd0-78d2-4988-b7f3-23214dc5a602
content-type: application/json

### create()
POST http://localhost:3000/qrcodes
content-type: application/json

{
    "type": "qr",
    "data": "{type: 'qr', data: 'https://www.google.com'}"
}

### update()
PATCH http://localhost:3000/qrcodes/6fa03cd0-78d2-4988-b7f3-23214dc5a602
content-type: application/json

{
    "type": "ean_13",
    "data": "{\"type\": \"qr\", \"data\": \"https://www.google.com\"}"
}

### delete()
DELETE http://localhost:3000/qrcodes/6fa03cd0-78d2-4988-b7f3-23214dc5a602
content-type: application/json



### Google Cloud Run
GET https://backend-1097962137391.us-central1.run.app
content-type: application/json

### QRCode
### findAll()
GET https://backend-1097962137391.us-central1.run.app/qrcodes
content-type: application/json

### findOne()
GET https://backend-1097962137391.us-central1.run.app/qrcodes/6fa03cd0-78d2-4988-b7f3-23214dc5a602
content-type: application/json

### create()
####Parâmetro data deve ser uma string.
POST https://backend-1097962137391.us-central1.run.app/qrcodes
content-type: application/json

{
    "type": "qr",
    "data": "{\"type\": \"qr\", \"data\": \"https://www.google.com\"}"
}

### update()
PATCH https://backend-1097962137391.us-central1.run.app/qrcodes/6fa03cd0-78d2-4988-b7f3-23214dc5a602
content-type: application/json

{
    "type": "ean_13",
    "data": "{\"type\": \"qr\", \"data\": \"https://www.google.com\"}"
}

### delete()
DELETE https://backend-1097962137391.us-central1.run.app/qrcodes/6fa03cd0-78d2-4988-b7f3-23214dc5a602
content-type: application/json