FROM node:22-alpine

# USER node

WORKDIR /backend

COPY package*.json ./

RUN npm install

COPY . .

RUN npx prisma generate

CMD ["npm", "run", "start"]

# Expõe as portas do NestJS (3000) e do Prisma Studio (5555)
EXPOSE 3000 5555

